package.json

This tiny pull request replaces `MIT/X11` with just `MIT` in package.json, so you won't get a validation warnings about a non-[SPDX](http://spdx.org/licenses) license identifier.

Set license to "MIT" in package.json

---

lib/portfinder.js

This fixes the removal of `options.host` that is always happening because the loop starts from `0` instead of `1`. It also stops the check as soon as a duplicate is found.

Fix wrong duplicate removal

---

lib/portfinder.js
test/port-finder-test.js

Remove ipv6 from default hosts that we test each port against 
to allow portfinder to work with machines that dont have ipv6
fixes #26 #28

Remove ipv6 from default hosts on failure

---

lib/portfinder.js
test/helper.js

- allow portfinder.getPort for all ports w/ os.networkInterfaces().internal === true
- allow portfinder.getPort from netmask 255.255.255.0, which maps to 
ip address given to default interface of machine (en0)
- allow portfinder.getPort to work from within a locally running VM assuming
vnic0 or vnic1 use netmask 255.255.255.0 (aka, shared or bridged mode)
- handle 0.0.0.0 host that while not output by os.networkInterfaces() is
nonetheless a bindable host that exists and must be handled accordingly
cc @indexzero or @stefanpenner - need at least one pair of eyeballs on this one. Thanks!

Handle MacOS 10.11.5+ interface changes and VM use case

---

lib/portfinder.js
test/helper.js

Issue #34 that arose out of portfinder 1.0.4 is a breaking change. Revert. We'll approach this in a more conservative fashion in an upcoming (likely) major release.

Revert changes pushed in 1.0.4

---

.travis.yml
appveyor.yml
lib/portfinder.js
package.json
test/helper.js
test/port-finder-multiple-test.js
test/port-finder-test.js
test/port-finder-z-integration-test.js

Catch EADDRNOTAVAIL to filter out non-bindable hosts before iterating through ports
The general idea here is to filter out non-bindable hosts prior to looking for an open port so that we don't try to guess what hosts are bindable. 
Specifically worth noting though is that **the way this works does not actually filter all hosts before trying to find a port, it interleaves the two**. In practice however, the interfaces produced by `os.networkInterfaces()` are ordered from least to most likely to 'be bindable' so for most imaginable use cases, the port found will be 'the next open port for all bindable hosts' on the machine. There are cases however, for example when binding to an address from the "host machine" -> VM, where catching `EADDRNOTAVAIL` will (for example) discard 2 potentially …

Catch eaddrnotavail

---

lib/portfinder.js
test/port-finder-z-integration-test.js

- Windows 10 native shell(#39) was rebinding to already bound ports. We
now send a message from a socket client -> server -> client to ensure
a host + port are actually open
- Windows 10 bash shell falls back to using 0.0.0.0 as the only host we
check in order to prevent throwing a syscall error as being tracked here:
https://github.com/Microsoft/BashOnWindows/issues/468
fixes: #39
closes: #41
fixes: https://github.com/ember-cli/ember-cli/issues/6338

Fix windows 10 support

---

lib/portfinder.js

Usage of non-supported operation under Windows Subsystem for Linux
os.networkInterfaces(), line 395, throws a not supported error on WSL (bash for windows). 
The operation will be supported at some point, but for now, I would want it to not crash and just return default values.

Don't bail when os.networkInterfaces is not supported.

---

README.md
lib/portfinder.d.ts
lib/portfinder.js
test/port-finder-test.js

Adds `getPortPromise()` which returns a Promise to the next available port : 
``` js
const portfinder = require('portfinder');
portfinder.getPortPromise()
.then((port) => {
//
// `port` is guaranteed to be a free port
// in this scope.
//
})
.catch((err) => {
//
// Could not get a free port, `err` contains the reason.
//
});
```

Promise support

---

test/port-finder-socket-test.js

Without this I see the tests (with node 6.10.2) completing but then just hanging because the servers are still listening on the sockets.

Make test close listening sockets instead of just removing them

---

lib/portfinder.js

Hi! Got a strange error while working on an angular app. For some reason, when I try to get the server up it throws the error below.
Obviously, when it receives '8080', everything crashes and according to exports.basePort options.port always should be of a number type.
~ ng s
│net.js:1487
│      throw new errors.RangeError('ERR_SOCKET_BAD_PORT', options.port);
│      ^
│
│RangeError [ERR_SOCKET_BAD_PORT]: Port should be > 0 and < 65536. Received 80801.
│    at Server.listen (net.js:1487:13)
│    at Object.internals.testPort (/<projectPath>/node_modules/portfinder/lib/portfinder.js:69:18
│)
│    at Server.onError (/<projectPath>/node_modules/portfinder/lib/portfinder.js:60:15)
│    at Object.onceWrapper (events.js:254:19)
│    at Server.emit (events.js:159:13)
│    at emitErrorNT …

Update portfinder to convert option.port to number

---

lib/portfinder.js

_for example:_ 
old :
```
// my-server
let server  = net.createServer(function(){});
server.listen(3000);
portfinder.basePort = 3000;
portfinder.getPort(function(error, port) {
// port -> 3000
});
```
now :
```
// my-server
let server  = net.createServer(function(){});
server.listen(3000);
portfinder.basePort = 3000;
portfinder.getPort(function(error, port) {
// port -> 3001
});
```
**Has passed the test.**

fixed port is not detects without host.

---

package-lock.json
package.json

Current npm will warn or error when asked to install dev dependencies
due to an outdated version of vows which has a potential DoS flaw.
https://nodesecurity.io/advisories/118

Upgrade vows to avoid security warning.

---

lib/portfinder.js
test/helper.js
test/port-finder-test.js

Right now, calling `getPort` when _every_ port above the given port is in use will throw:
```
RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 65536.
```
This isn't passed to the callback - it's thrown directly by node. Because this isn't handled at all that will usually crash the whole node process.
To easily reproduce this, start a server on port 65535 (the maximum port), and then run `portfinder.getPortPromise({ port: 65535 })`.
This happens because `testPort` is unbounded, and constantly tries ports until it finds an available one, without checking whether the port to test is valid, so when 65535 is in use it tries to test 65536, which isn't a valid port.
This PR makes `testPort` instead check whether the next port is valid before testing it, so that it …

Avoid crashing if all ports above the start port are unavailable

---

README.md
lib/portfinder.js
test/port-finder-multiple-test.js
test/port-finder-test.js

Addresses https://github.com/http-party/node-portfinder/issues/79 by creating an array of candidate ports to test and randomly shuffling it. The remaining logic is unchanged, except that the check for whether a tested port exceeds the global highestPort is moved from testPort to getPort (i.e. we exclude any port higher than highestPort from the initial list of candidate ports).

Randomize selection order of tested ports

---

README.md

[![Build Status](https://api.travis-ci.org/indexzero/node-portfinder.svg)](https://travis-ci.org/indexzero/node-portfinder)
↓
[![Build Status](https://api.travis-ci.org/http-party/node-portfinder.svg)](https://travis-ci.org/http-party/node-portfinder)

fix(docs): follow repo url change for travis ci badge

---

package-lock.json

Update `mkdirp` to 0.5.5 which in turn updates `minimist` to 1.2.5
which addresses:
https://www.npmjs.com/advisories/1179

mkdirp: 0.5.5

---

package.json

Hi!
I see that in PR #101 you bumped-up the version of `mkdirp` to 0.5.5 which in turn updates `minimist` to 1.2.5
which addresses https://www.npmjs.com/advisories/1179
Problem is that this PR only updated `package-lock.json` and not `package.json` that remains at 0.5.1. As `package.json` still depends on `mkdirp` 0.5.1, when we get `node-portfinder` as a dependency, we still get an old version of `minimist`.

Fix #108 - Bumping up mkdirp version to 0.5.5

---

lib/portfinder.d.ts

Was causing warning about missing property.
Signed-off-by: Bruno Gaspar <brunofgaspar1@gmail.com>

Add missing highestPort property to TypeScript definition

---

README.md
lib/portfinder.d.ts
lib/portfinder.js

Ran into a compiler error when using portfinder in TypeScript. Module exports are considered immutable in typescript, so the following code won't compile:
```
import * as portfinder from "portfinder";
portfinder.basePort = 3000;
```
Instead, a new accessor method allows us to say `portfinder.setBasePort(3000);`

Add mutator methods to allow ports ranges to be set with module-style imports

---

package.json

PR bumps the version of `async` dependency in package.json so that it's not possible to get a vulnerable version of `async` via this dependency. #130 only bumped the version in the `package-lock.json` file which only affects this repository, and not downstream consumers.

Bump version of async in package.json

---

test/port-finder-socket-test.js

`exec` or `glob` were not being used in this test file, and so I've removed the import of them. This looks to be the only file that had unused imports.

Remove unused test imports

---

test/port-finder-socket-test.js

PR adds a test case that validates the recursive mkdir behavior that currently exists within the `getSocket` function. This helps demonstrate the breaking change in #134 which removes `mkdirp` in favor of the builtin `fs.mkdir` where for node < 10.12, the `recursive` flag didn't exist, and so it would not behave the same as `mkdirp`. To demonstrate that, I merged this code onto the `modernize` branch in my fork to trigger CI, and where all node < 10.x fail: https://github.com/MasterOdin/node-portfinder/actions/runs/2782492617.

Add test around recursively making socket directory

---

.github/workflows/ci.yml
package-lock.json
package.json

supersedes #134 
closes #134 
This PR contains a few simple commits meant to modernize the dependencies that had security vulnerabilities in them.
It also contains some code from @MasterOdin that attempts to fix the test setup. Note that I have left (but upgraded) mkdirp for now. We can revisit that a week from now. I will not be in town next week, so this release needs to be minimal as to not interrupt my vacation :). 
With only dependency updates included in the main code, things should not change behavior wise in any shape or form. This should be completely safe and non breaking to merge. I will do so now, and make a release.
cc @MasterOdin fyi
ps tests all pass :) - we probably don't need the recursive fs.rmdir code but let me know your thoughts - it's only for the tests and I need to …

Modernize2

---

lib/portfinder.js

Hi,
I was reading the source code for personal interest and found that you are using a loop to check if the host is unique. I think indexOf() could be much faster than the loop. Here is the comparison on my laptop:
loop: 4.363ms
indexOf: 0.005ms

refactor: using indexOf to check unique host

---

lib/portfinder.d.ts

The typescript definition was missing the `function` keyword.

fix(types): fixed typescript definition

---

.github/workflows/ci.yml

This PR modifies the current CI so that it runs the typescript compiler over the `portfinder.d.ts` file to minimally check that it's valid TS. A potential further step would be to use something like [tsd](https://www.npmjs.com/package/tsd) to write unit tests on the types, but the types here are relatively simple that I'm not sure how much benefit that'd bring.
This PR will currently fail the new CI step ([test run](https://github.com/http-party/node-portfinder/runs/7727997530?check_suite_focus=true)) until #139 is merged. Once #139 is merged, I'll rebase `master` onto this branch and it should then now pass.
Also, this PR only makes sense if #140 were to be rejected.

Test TS types in CI

---

lib/portfinder.d.ts

PR adds a return signature of `void` to the `setBasePort` and `setHighestPort` functions added in #115. Without these, TS will implicitly type them as a `any`, which then allows someone to do anything with the "return value" in TS, losing some of the protections TS gives.
Sorry @eriktrom that I didn't catch this while I put together #141 and was looking at this function and so could have gone in 1.0.30 release.

Add TS return signature to setPort functions

---

.github/workflows/ci.yml

PR adds the `--strict` flag to the tsc typechecking that the CI was doing. This increases the strength of typechecking (see https://www.typescriptlang.org/tsconfig#strict for full details), but for this particular case, it's mostly just for catching no implicit any usage. An alternative would be to use `--noImplicitAny` flag instead, but it doesn't hurt to have tsc validate the definition file is as strict as possible even if some of the stuff doesn't really apply.
Note, this PR will fail until #143 is merged.

Add strict flag to CI TS typechecking

---

lib/portfinder.js

With the current implementation, there is a chance that a user binds a socket on a port (that was reported as being available) although the server (created to check whether that port is available) is not fully closed yet. This causes the binding to fail, because the port is still in use.
In this PR, we change the implementation such that the the callback passed to the `testPort` is invoked when the server is fully closed. Thanks to @sla89 for the idea!
Unfortunately, we didn't manage to write a unit tests that reliably verifies the correct behavior. I'm open for ideas ;)

Wait until server is closed before invoking callback

---

.github/workflows/ci.yml

Exclude macos-latest, node-version 0.12.x, 4.x, 6.x, 8.x, 10.x, 12.x, 14.x from running on CI to prevent the failure:
`Unable to find Node version 'y.x' for platform darwin and architecture arm64.`

Update .github/workflows/ci.yml to exclude macOS for old versions of node

---

lib/portfinder.d.ts
lib/portfinder.js
test/port-finder-multiple-test.js

PR adds a new `getPortsPromise` function to allow using a promisified version of `getPorts`, similar to how there's a `getPortPromise` version of `getPort`. A test is included for the function, which mimics what I saw for testing `getPortPromise`.
I also fixed a type error which made it seem like the `options` parameter was required for `getPorts`, where it's optional, just need to always pass the `count` and `callback`.

Add promise version of getPorts function

---

lib/portfinder.js

PR fixes a bug reported in https://github.com/http-party/node-portfinder/pull/120#issuecomment-1502633024, where the current `indexOf` check will only succeed if `options.host` was already in `exports._defaultHosts`, as opposed to the desired behavior of appending it if it's _not_ in the array.
I've also cleaned up the nested conditional to just be one level as the nesting was not necessary.

Fix adding options.host to defaultHosts list

---

package-lock.json
package.json
test/helper.js
test/port-finder-socket.test.js

Closes #153 
PR updates async dependency to latest version. The only change that really affects this library was that the first function argument to [`whilst`](https://caolan.github.io/async/v3/docs.html#whilst) now has a callback function that need to call to return the test result, vs just returning it as before with v2.
Per the discussion in the linked issue, need to drop support for Node <= 4 as async dropped support for those versions of node.

Update async to ^3.2.6

---

README.md
lib/portfinder.js

PR drops the code checks for promise support as support for promises was added in node 4.

Remove check for promise support

---

lib/portfinder.js
test/getPort.js
test/helper.js
test/port-finder-integration.test.js
test/port-finder-multiple.test.js
test/port-finder-socket.test.js
test/port-finder.test.js

PR replaces usage of `var` with `const`/`let` which were introduced in Node 6. I didn't touch the `var` in the README as that was done in #154.

Replace var with const/let

---

package-lock.json
package.json

PR updates the library to use `debug:^4.3.6` as dependency. This is the latest version (it's 2 behind), but I chose this version as it's the latest version that fixed JS deprecations or reported vulnerabilities, while still giving a bit of leeway to folks to dedupe if they already have a recentish version of debug installed.
There are no direct tests for debug, so I tested it by doing `DEBUG=portfinder:* npm run test` and confirming that the output remained the same between versions.

Update debug to 4.3.6

---

.github/workflows/ci.yml
lib/portfinder.js
package.json

Closes #163 
PR removes the `mkdirp` dependency relying on `{ recursive: true }` for `fs.mkdir` which has the same behavior. This necessitated bumping the supported node version to 10.12 as that's the version of Node that added this feature.
Note, I did not remove the recursive folder removal in the socket test (https://github.com/node-portfinder/node-portfinder/blob/b64ab4f707fccc079da3f86716ec0c78be61a30b/test/port-finder-socket.test.js#L68-L76) as `recursive` was added to [`fs.rmdir`](https://nodejs.org/api/fs.html#fsrmdirpath-options-callback) in 12.10, and then they deprecated that option and added the [`fs.rm`](https://nodejs.org/api/fs.html#fsrmpath-options-callback) function in 14.14.

Remove mkdirp dependency

---

lib/portfinder.js
test/port-finder-multiple.test.js
test/port-finder.test.js

PR fixes a bug introduced by #168 where when passing `options` to the `getPort` or `getPorts` function and no callback, then the options object would be assigned to the callback, and the whole thing would break.
As part of this, I've refactored the test suite so that all `getPort` and `getPorts` tests are now called for the callback and promise variants of the functions.

Fix returning promise with passing options

---

lib/portfinder.js
test/port-finder.test.js

if `startPort` is provided by user, actually use it

---

lib/portfinder.d.ts
lib/portfinder.js
test/port-finder-socket.test.js

Closes #169 
Adds a promise return for `getSocket` as well as `getSocketPromise` function, so as to match the `getPort` and `getPorts` functions. Also adds type information for these functions as that was totally missing before.
The overall tests that are run remain the same, just that they're run against all three variants as was setup in #172.

Add promise return for getSocket

---

lib/portfinder.js
test/port-finder.test.js

Fixes #171 
PR makes it so that instead of having `getPort` throw errors in some cases, it'll instead return an error on the callback. This allows for a singular error handling necessary for end users (namely around the callback), vs requiring them to both worry about the callback as well as wrapping the `getPort` call in a try/catch.
I think that there's more options validation that could happen here (e.g. if `options.startPort` is provided, should probably have similar checks), but that can be done in a follow-up once this pattern is established on how to return errors to the user.

Return callback error vs throwing
